const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const archiver = require('archiver');
const { getIdeas, updateIdeaStatus, saveAsset, initSchema } = require('../utils/db');
const { generateContent } = require('./llm');

const ARTIFACTS_DIR = path.join(__dirname, '../products');

async function createProduct() {
    initSchema();
    const ideas = getIdeas('new');

    if (ideas.length === 0) {
        console.log('No new ideas to process.');
        return;
    }

    const idea = ideas[0];
    console.log(`Processing idea: ${idea.title}`);

    // Determine type
    const isCode = /tool|bot|script|app|generator/i.test(idea.title);
    const type = isCode ? 'micro-saas' : 'product'; // 'product' = info-product here

    console.log(`Detected type: ${type}`);

    try {
        if (type === 'product') {
            await createPDF(idea);
        } else {
            await createCodePackage(idea);
        }

        updateIdeaStatus(idea.id, 'processed');
        console.log(`Successfully created product for idea ${idea.id}`);

    } catch (e) {
        console.error(`Failed to create product for idea ${idea.id}:`, e);
        updateIdeaStatus(idea.id, 'error');
    }
}

async function createPDF(idea) {
    const content = await generateContent(`
        Write a short e-book about: "${idea.title}".
        Source context: ${idea.content || idea.title}
        
        Structure:
        1. Introduction
        2. Top 5 Tips
        3. Conclusion
        
        Keep it concise (approx 500 words).
    `);

    const filename = `ebook_${idea.id}.pdf`;
    const filePath = path.join(ARTIFACTS_DIR, filename);

    const doc = new PDFDocument();
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    doc.fontSize(25).text(idea.title, { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(content, { align: 'justify' });

    doc.end();

    await new Promise(resolve => stream.on('finish', resolve));

    saveAsset({
        name: idea.title,
        type: 'pdf',
        description: `E-book generated from idea: ${idea.title}`,
        status: 'draft'
    });

    console.log(`Generated PDF: ${filePath}`);
}

async function createCodePackage(idea) {
    const code = await generateContent(`
        Write a simple Node.js script for: "${idea.title}".
        Source context: ${idea.content || idea.title}
        
        Only provide the code block. No explanation.
        include package.json dependencies at the top as a comment like // DEPS: express, axios
    `);

    const cleanCode = code.replace(/```javascript|```/g, ''); // Basic cleanup

    const filename = `tool_${idea.id}.zip`;
    const filePath = path.join(ARTIFACTS_DIR, filename);
    const output = fs.createWriteStream(filePath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('close', function () {
        console.log(archive.pointer() + ' total bytes');
        console.log('archiver has been finalized and the output file descriptor has closed.');
    });

    archive.pipe(output);
    archive.append(cleanCode, { name: 'index.js' });
    archive.append(JSON.stringify({ name: "tool", version: "1.0.0", main: "index.js" }, null, 2), { name: 'package.json' });
    archive.append(`# ${idea.title}\n\nGenerated by BizBot.`, { name: 'README.md' });

    await archive.finalize();

    saveAsset({
        name: idea.title,
        type: 'code',
        description: `Code tool generated from idea: ${idea.title}`,
        status: 'draft'
    });

    console.log(`Generated Zip: ${filePath}`);
}

if (require.main === module) {
    createProduct();
}

module.exports = { createProduct };
