// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CloneModelAsTemplateReducer from "../clone_model_as_template_reducer";
import CreateModelReducer from "../create_model_reducer";
import CreateRowReducer from "../create_row_reducer";
import DeleteModelReducer from "../delete_model_reducer";
import DeleteRowReducer from "../delete_row_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import UpdateModelReducer from "../update_model_reducer";
import UpdateRowReducer from "../update_row_reducer";

export type CloneModelAsTemplateParams = __Infer<typeof CloneModelAsTemplateReducer>;
export type CreateModelParams = __Infer<typeof CreateModelReducer>;
export type CreateRowParams = __Infer<typeof CreateRowReducer>;
export type DeleteModelParams = __Infer<typeof DeleteModelReducer>;
export type DeleteRowParams = __Infer<typeof DeleteRowReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type UpdateModelParams = __Infer<typeof UpdateModelReducer>;
export type UpdateRowParams = __Infer<typeof UpdateRowReducer>;

