// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Model = __t.object("Model", {
  id: __t.u64(),
  name: __t.string(),
  owner: __t.identity(),
  fieldsJson: __t.string(),
  description: __t.string(),
  visibility: __t.string(),
  createdAt: __t.timestamp(),
});
export type Model = __Infer<typeof Model>;

export const Profile = __t.object("Profile", {
  identity: __t.identity(),
  displayName: __t.string(),
  createdAt: __t.timestamp(),
});
export type Profile = __Infer<typeof Profile>;

export const Row = __t.object("Row", {
  id: __t.u64(),
  modelId: __t.u64(),
  dataJson: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Row = __Infer<typeof Row>;

