"""
Scheduler Module
Manages cron-based scheduling for autonomous content creation.
"""

import subprocess
import os
from pathlib import Path
from datetime import datetime

CRON_COMMENT = "# Auto-generated by Content Agent Scheduler"
SCRIPT_PATH = Path(__file__).parent.parent / "run.py"
VENV_PATH = Path(__file__).parent.parent / ".venv" / "bin" / "python"
LOG_DIR = Path(__file__).parent.parent / "logs"


def ensure_log_dir():
    LOG_DIR.mkdir(parents=True, exist_ok=True)


def get_cron_entries() -> list:
    """Get current cron entries related to our scheduler."""
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True, timeout=10)
    if result.returncode != 0:
        return []
    return [line for line in result.stdout.split("\n") if CRON_COMMENT in line]


def set_daily_schedule(hour: int = 9, minute: int = 0) -> bool:
    """
    Set up daily content creation schedule.
    Default: runs at 9:00 AM daily.
    """
    ensure_log_dir()

    # Get existing crontab
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True, timeout=10)
    existing = result.stdout if result.returncode == 0 else ""

    # Remove any existing entries from our scheduler
    lines = [l for l in existing.split("\n")
             if CRON_COMMENT not in l and l.strip()]

    # Add new schedule
    log_file = LOG_DIR / f"cron_{datetime.now().strftime('%Y%m%d')}.log"
    cron_line = f"{minute} {hour} * * * cd {SCRIPT_PATH.parent} && {VENV_PATH} {SCRIPT_PATH} >> {log_file} 2>&1 {CRON_COMMENT}"

    lines.append(cron_line)
    new_crontab = "\n".join(lines) + "\n"

    # Write new crontab
    proc = subprocess.run(["crontab"], input=new_crontab,
                          capture_output=True, text=True, timeout=10)

    if proc.returncode == 0:
        print(f"  ✓ Daily schedule set: {hour:02d}:{minute:02d}")
        print(f"  ✓ Logs: {log_file}")
        return True
    else:
        print(f"  ✗ Failed to set schedule: {proc.stderr}")
        return False


def set_multiple_daily(times: list = None) -> bool:
    """
    Set multiple daily schedules in one crontab write.
    times: list of (hour, minute) tuples.
    """
    if times is None:
        times = [(9, 0), (15, 0), (21, 0)]  # 9am, 3pm, 9pm

    ensure_log_dir()

    # Get existing crontab (non-scheduler entries only)
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True, timeout=10)
    existing_lines = []
    if result.returncode == 0:
        existing_lines = [l for l in result.stdout.split("\n")
                          if CRON_COMMENT not in l and l.strip()]

    # Add all scheduler entries
    log_file = LOG_DIR / f"cron_{datetime.now().strftime('%Y%m%d')}.log"
    for hour, minute in times:
        cron_line = f"{minute} {hour} * * * cd {SCRIPT_PATH.parent} && {VENV_PATH} {SCRIPT_PATH} >> {log_file} 2>&1 {CRON_COMMENT}"
        existing_lines.append(cron_line)

    new_crontab = "\n".join(existing_lines) + "\n"
    proc = subprocess.run(["crontab"], input=new_crontab,
                          capture_output=True, text=True, timeout=10)

    if proc.returncode == 0:
        for hour, minute in times:
            print(f"  ✓ Daily schedule set: {hour:02d}:{minute:02d}")
        print(f"  ✓ Logs: {log_file}")
        return True
    else:
        print(f"  ✗ Failed to set schedule: {proc.stderr}")
        return False


def clear_schedule() -> bool:
    """Remove all scheduler entries from crontab."""
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True, timeout=10)
    if result.returncode != 0:
        return True  # No crontab to clear

    lines = [l for l in result.stdout.split("\n")
             if CRON_COMMENT not in l and l.strip()]
    new_crontab = "\n".join(lines) + "\n"

    proc = subprocess.run(["crontab"], input=new_crontab,
                          capture_output=True, text=True, timeout=10)
    return proc.returncode == 0


def show_schedule() -> list:
    """Show current scheduled jobs."""
    entries = get_cron_entries()
    if not entries:
        print("  No active schedules")
        return []

    print(f"  Active schedules ({len(entries)}):")
    for e in entries:
        parts = e.split()
        schedule = f"{parts[0]} {parts[1]} {parts[2]} {parts[3]} {parts[4]}"
        print(f"    ⏰ {schedule}")
    return entries


if __name__ == "__main__":
    import sys
    action = sys.argv[1] if len(sys.argv) > 1 else "show"

    if action == "set":
        set_daily_schedule()
    elif action == "set-multi":
        set_multiple_daily()
    elif action == "clear":
        clear_schedule()
    elif action == "show":
        show_schedule()
    else:
        print(f"Unknown action: {action}")
        print("Usage: python scheduler.py [set|set-multi|clear|show]")
